# Site settings
title: Margaret Heggan
email: Margaret.Heggan7@gmail.com
url: https://margaretHeggan.github.io/Data-Analytics-Portfolio
description: "A curated portfolio featuring data analysis, forecasting, and business intelligence projects by a data analytics professional."
keywords: "dataanalytics, data-visualization, revenue-forecasting, portfolio, pricing-strategy"
skills: "Turning Data into Insight, and Insight into Action - Analyst - Strategic Forecasting"
meta_author: Margaret Heggan

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2ec4b6 #80B3FF
  primary-rgb: "46,196,182" #"128,179,255"
  secondary: ff3366 #FD6E8A
  secondary-dark: 011627 #A2122F

# Footer settings
footer:
  copyright: Margaret Heggan
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/margaret-heggan-8a987716/
  - title: github
    url: https://github.com/margaretheggan

# Email Address (make sure to include "mailto:" before your email!)
email:
  email-url: mailto:Margaret.Heggan7@gmail.com

# Postal address (add as many lines as necessary)
location:
  - line: Houston, Texas

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.
Cyber icons created by <a href="https://www.flaticon.com/free-icons/cyber-attack" title="cyber attack icons">Freepik - Flaticon</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
